apiVersion: apps/v1
kind: Deployment
metadata:
  name: count
spec:
  replicas: 2
  selector:
    matchLabels:
      run: count
  template:
    metadata:
      labels:
        run: count
    spec:
      containers:
      - image: sasmita25/sample
        name: count
        ports:
        - containerPort: 3000
